name: Run instrumented tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-test-aer:
    name: "Android Emulator Runner"
    runs-on: macos-latest
    timeout-minutes: 80

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          profile: Galaxy Nexus
          disable-animations: true
          disk-size: 2000M
          heap-size: 600M
          script: |
            adb logcat -c
            adb logcat > logcat.txt &
            ./gradlew installDebug
            maestro test .github/maestro

      - name: Save Test Results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results
          path: |
            /Users/runner/work/alkaa/alkaa/app/build/reports/androidTests/
            ./logcat.txt
          retention-days: 7
